### ISSUE TITLE
[EPIC] Runbook

### ISSUE THREAD

**Issue by cjimison** [RoosterShip/wrilya#38]
### Summary

Create a collection of Runbooks for our usage.

### Description

DevOps is so easy to forget how things work,   There are commands to execute and it is constantly growing as new aspects are considered.  With this in mind I want to create a collection of Runbooks to call out the current state of DevOps system and how to execute steps that might have been forgotten.

### Goal

- Archive of knowledge and steps
- Ability for others to review and ramp up security
- Check the question if it make sense to keep devops scripts in an OpenSource DB

### stakeholders

- @cjimison 

### Requirements

- [ ] I can read a document explaining how to allocate a new cluster
- [ ] I can read a document explaining how to deploy a build to the cluster
- [ ] I can read a document explaining how secret management works
- [ ] I can read a document explaining about each service that runs and why it is there
- [ ] I can read a document on how to setup GCP access, etc.
- [ ] I can read a document on how the CI/CD system works

### Dependencies

- [x] Working Deployment System
- [x] Working CICD System

### Risks

- This might expose too much info.  However it does really remove the idea of security via obscurity
- Documentation need to be maintained.

### Acceptance Criteria

- [ ] I can read a document explaining how to allocate a new cluster
- [ ] I can read a document explaining how to deploy a build to the cluster
- [ ] I can read a document explaining how secret management works
- [ ] I can read a document explaining about each service that runs and why it is there
- [ ] I can read a document on how to setup GCP access, etc.
- [ ] I can read a document on how the CI/CD system works

### Stories

- [x] #39
- [x] #40 
- [ ] #41
- [ ] #42
- [ ] #43
- [ ] #44

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct
