### ISSUE TITLE
[STORY] GCP Cluster Allocation

### ISSUE THREAD

**Issue by cjimison** [RoosterShip/wrilya#39]
### Summary

As a DevOps user I can read a document that shows me the steps to allocating a GCP Cluster using our Pulumi setup.

### Description

We use Pulumi to allocate GCP cloud services.  There are many hidden things when getting this all setup such as your local environment, state files, etc.  This document should explain to a new user how to get all that setup and allocate a GCP cluster

### Acceptance

- Document showing setup of Pulumi and GCP access
- Document reviewing Pulumi cluster allocation

### Dependencies

- Working knowledge of our current system.

### Task

- [ ] Create new markdown file on how to setup Pulumi
- [ ] Create new markdown file on how to access GCP services
- [ ] Create new markdown file on how to deploy new cluster and shut it down

### Epic

GH-38
