### ISSUE TITLE
[STORY] DevOp Runbook for Deploying Clusters

### ISSUE THREAD

**Issue by cjimison** [RoosterShip/wrilya#40]
### Summary

As a DevOps user I want to have a document explaining how to deploy new builds to the cluster.

### Description

A documented set of steps on how to deploy a cluster to a GKE environment.

### Acceptance

- [ ] Github markdown file for deployment of cluster and configurations

### Dependencies

- #39 
- Working knowledge of the system

### Task

- [ ] Create new Github document
- [ ] Section on how Pulumi "stacks" vs "namespaces" vs "clusters" work
- [ ] Steps for deploying an application cluster
- [ ] Steps for updating an application cluster
- [ ] Steps for deleting an application cluster

### Epic

GH-38
