### ISSUE TITLE
[STORY] Runbook for Secrets

### ISSUE THREAD

**Issue by cjimison** [RoosterShip/wrilya#41]
### Summary

As a DevOps user I will need to upload secrets.  I would like a document explaining out how manage our secrets 

### Description

Secrets get lost all the time and end up all over the place.  This document is meant to talk about how we manage our secrets and where they can be found.

### Acceptance

- [ ] Github markdown document outlining secret mangement

### Dependencies

- knowledge of system

### Task

- [ ] Cover Pulumi secrets
- [ ] Cover GCP Secrets
- [ ] Cover Github secrets
- [ ] Document in google docs our current secrets.

### Epic

GH-38
