### ISSUE TITLE
[STORY] Active Service Architecture

### ISSUE THREAD

**Issue by cjimison** [RoosterShip/wrilya#42]
### Summary

As any user I would like to see a Service architecture diagram with an explanation of what each service does.

### Description

We use a lot of different services.  While we are not really a "microservice" architecture we are also not a "macroservice".  Kind of a 50/50 so have a good description of each service can be very helpful.

### Acceptance

- [ ] Github markdown document describing the architecture used and what each service does

### Dependencies

- Knowledge of the system

### Task

- [ ] Architecture Diagram
- [ ] Architecture walkthrough with some sequence diagrams
- [ ] Quick description of what each service does
- [ ] Data storage document

### Epic

GH-38
