### ISSUE TITLE
[STORY] GCP Setup and access

### ISSUE THREAD

**Issue by cjimison** [RoosterShip/wrilya#43]
### Summary

As a new DevOps engineer I would like an easy to use guide on how to get setup with GCP access.

### Description

Getting GCP setup correctly is both easy and hard.  There are always some CLI command you have to re-enter each day for access or other little thing.  This document calls out our GCP usage and how new Roostership employees can access it.

### Acceptance

- [ ] I can read a google doc covering what I need to know to get setup with GCP and execute our DevOps commands.

### Dependencies

- Working knowledge of the system.

### Task

- [ ] Create Github markdown document covering GCP commands
- [ ] Create section in document calling GCP services we use
- [ ] Call out contact steps for new folks getting access to GCP

### Epic

GH-38
