### ISSUE TITLE
[STORY] DevOps CI/CD

### ISSUE THREAD

**Issue by cjimison** [RoosterShip/wrilya#44]
### Summary

As a DevOps user I would like to have a document that reviews our CI/CD system.

### Description

A simple document that describes how the current CI/CD system work and where we would like to move it to in the future.

### Acceptance

- [ ] Github Markdown document for CI/CD created
- [ ] Section describing the current CI/CD "Flow"
- [ ] Section describing the future CI/CD "Flow"

### Dependencies

- Working knowledge of the system

### Task

- [ ] Create Github Markdown document for CI/CD created
- [ ] Add Section describing the current CI/CD "Flow"
- [ ] Add Section describing the future CI/CD "Flow"

### Epic

GH-38
