### ISSUE TITLE
[TASK] Clean up issue template

### ISSUE THREAD

**Issue by cjimison** [RoosterShip/wrilya#45]
### Description

After the first pass of creating tickets I there is some slight cleanup I want to get done.

### Dependencies

- None

### Subtask

- [x] Remove the colon from the [EPIC], [STORY] and [Task] templates
- [x] Remove the "Requirements" section from the epic.  It is covered the Acceptance Criteria.
- [x] Review Bug template for any updates

**Comment by cjimison** [comment]
Completed with commit: 85739d90afe212af49489aaf5c948d861d5d40c8
